output_folder: "C:\\data\\2204-5190218"
context: "The context is sequence of articles about a modeling processing using UML diagrams and IDEF5 Ontology Description Capture Method describing for how to do general modeling tasks and modeling for analysts new to a unified and collaborative modeling practice."
objects:
  - prompt: "Explain in detail and without using adverbs or adjectives. Include industry specific examples. Look at how to get started with a modeling process beginning with the phases of modeling. This introduction is about a book that covers a modeling process using model standards such as UML, IDEF5, and Gane-Sarson DFDs"
    title: "Introduction to a Modeling process using model standards such as UML, IDEF5, and Gane-Sarson DFDs"
    filename: "001-introduction.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, model process - Initiation Phase'"
    title: "Initiation Phase"
    filename: "002-initiation.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, model process - Conceptualization Phase"
    title: "Conceptualization Phase"
    filename: "003-conceptualization.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, model process - Analysis Phase"
    title: "Analysis Phase"
    filename: "004-analysis-phase.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, model process - Design Phase"
    title: "Design Phase"
    filename: "005-design.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, model process - Implementation Phase"
    title: "Implementation Phase"
    filename: "006-implementation.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, model process - Deployment Phase"
    title: "Deployment Phase"
    filename: "007-deployment.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, model process - Maintenance Phase"
    title: "Maintenance Phase"
    filename: "009-maintenance.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, Introduction to thinking in models"
    title: "Introduction to thinking in models"
    filename: "010-thinking-in-models.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, thinking in models - Brainstorming with a Group"
    title: "Brainstorming with a Group"
    filename: "011-brainstorming.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, thinking in models - Creating Artifacts for Review"
    title: "Creating Artifacts for Review"
    filename: "012-artifacts.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, thinking in models - Facilitating Review of Models"
    title: "Facilitating Review of Models"
    filename: "013-review.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, thinking in models - Revising Models"
    title: "Revising Models"
    filename: "014-revising.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, thinking in models - Maintaining Models"
    title: "Maintaining Models"
    filename: "015-maintaining-models.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, Introduction to UML Diagrams"
    title: "Introduction to UML Diagrams"
    filename: "016-intro-to-uml.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, UML - Using UML Diagrams - Use Case Diagrams"
    title: "Use Case Diagrams"
    filename: "017-use-case.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, UML - Class Diagrams"
    title: "Class Diagrams"
    filename: "019-class.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, UML - Sequence Diagrams"
    title: "Sequence Diagrams"
    filename: "020-sequence.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, UML - Activity Diagrams"
    title: "Activity Diagrams"
    filename: "021-activity.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, Introduction to IDEF5 Ontology Description Capture Method"
    title: "Introduction to IDEF5 Ontology Description Capture Method"
    filename: "022-intro-idef5.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, IDEF5 - Identify the Ontology Purpose and Scope"
    title: "Identify the Ontology Purpose and Scope"
    filename: "023-ontology.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, IDEF5 - Capture Ontology Description"
    title: "Capture Ontology Description"
    filename: "024-description.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, IDEF5 - Verify and Validate Ontology"
    title: "Verify and Validate Ontology"
    filename: "025-validate.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, IDEF5 - Integrate and Manage Ontology"
    title: "Integrate and Manage Ontology"
    filename: "026-integrate.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, Introduction to Gane-Sarson Data Flow Model Diagrams"
    title: "Introduction to Gane-Sarson Data Flow Model Diagrams"
    filename: "027-intro-to-dfd.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, Data Flow Model Diagram - Getting Started with Gane-Sarson DFDs"
    title: "Getting Started with Gane-Sarson DFDs"
    filename: "028-started-with-dfd.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, Data Flow Model Diagram - Detailed Design of Processes"
    title: "Detailed Design of Processes"
    filename: "029-design-with-dfd.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, Data Flow Model Diagram - External Entities and Interaction"
    title: "External Entities and Interaction"
    filename: "030-interfaces.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, Data Flow Model Diagram - Creating and Refining the Gane-Sarson DFD"
    title: "Creating and Refining the Gane-Sarson DFD"
    filename: "031-create-refine-dfd.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, Data Flow Model Diagram - Analyzing a System with Gane-Sarson DFDs"
    title: "Analyzing a System with Gane-Sarson DFDs"
    filename: "032-analyz-with-dfd.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, Data Flow Model Diagram - Case Study - Practical Application of Gane-Sarson DFDs"
    title: "Practical Application of Gane-Sarson DFDs"
    filename: "033-use-dfd.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, Data Flow Model Diagram - Tools and Software for Gane-Sarson DFDs"
    title: "Tools and Software for Gane-Sarson DFDs"
    filename: "034-dfd-software.md"
  - prompt: "Continue, in detail and without using adverbs or adjectives. Include industry specific examples, on the topic with an article and chapter on, Data Flow Model Diagram - Advanced Techniques and Best Practices"
    title: "Advanced Techniques and Best Practices"
    filename: "034-advanced-dfd.md"